### ISSUE TITLE
Hoàn thành đồ án

### ISSUE THREAD

**Issue by heraclex12** [heraclex12/IntroDS-final#1]
Hi,

Nhóm mình đã hoàn thành xong đồ án môn, hy vọng nhận được sự góp ý từ các bạn.

Hiếu.

**Comment by phan-anh-hao** [comment]
Chào mọi người, 
Theo em thì em có một vài đóng góp cho đồ án của nhóm mình như này ạ :
1. Đầu tiên em muốn góp ý là file README của nhóm mình nên bổ sung một vài thông tin đồ án (chủ đề, cảm hứng, ý nghĩa của mỗi file trong đồ án, nguồn,...)
2. Ngoài việc sử dụng thuật toán Logistic Regression thì mình nên sử dụng thêm nhiều thuật toán khác để có thể so sánh (Decision Tree, k-Nearest Neighbors,...), có thể giúp cải thiện độ chính xác của bài toán
3. Lúc em đọc report lúc  đọc câu hỏi mà nhóm đưa ra thì em không nghĩ là mọi người dùng poster (image) để dự đoán (em chỉ nghĩ là dựa trên nội dung :v), đây là điểm để mà em có thể học hỏi từ nhóm 💯 💯 🔝 
Đó là suy nghĩ của em, nếu có gì không đúng mong mọi người có thể góp ý ạ.

**Comment by heraclex12** [comment]
@phan-anh-hao Hi bạn,

Mình xin thay mặt nhóm cảm ơn bạn đã góp ý.

1. Mình sẽ cập nhật lại file README sớm nhất có thể.
2. Thực ra bọn mình đã có thử nghiệm vài mô hình khác như MLPClassifier, RandomForestClassifier. Tuy nhiên kết quả không cải thiện mấy so với LogisticRegression nhưng thời gian huấn luyện để tìm ra mô hình tốt nhất khá mất thời gian, nhóm mình sợ sẽ không kịp trong quá trình vấn đáp nên bọn mình đã không liệt kê. Đặc điểm của LogisticRegression rất thích hợp cho binary classification nên mình nghĩ kết quả vậy đã đủ ổn.
3. Thực ra do nhóm mình sợ không kịp hoàn thành mô hình xử lí ảnh nên đẩy lên trước mô hình ngôn ngữ. Lúc sau cập nhật mô hình ảnh lên thì không để ý tới câu hỏi :D Cảm ơn bạn đã nhắc nhở, mình sẽ sửa lại câu hỏi.

Nếu còn bất kì ý kiến đóng góp nào, bạn cứ thoải mái nói bọn mình nhé.

Hiếu

**Comment by Ryobinl** [comment]
Chào mọi người, em có một số góp ý về đồ án như sau:
1. Theo em nghĩ thì ngoài việc sử dụng thuộc tính overview để dự đoán , nếu có thời gian thì nhóm mình cũng nên thử với thuộc tính genres (cũng có thể ảnh hưởng ít nhiều đến mô hình).
2. Khi điều chỉnh các siêu tham số trong hyperparameter tuning thì ta nên vẽ heatmap để thấy được sự thay đổi của loss train và loss validation (điều chỉnh siêu tham số).

**Comment by heraclex12** [comment]
@Ryobinl Hi bạn,

Cảm ơn bạn đã góp ý.

1. Mình cũng có nghĩ tới genres, nhưng mà sợ là tổ hợp nào đó ví dụ action với romance thì không phân biệt được label. Trong trường hợp này thì rule-based approach có thể sẽ tốt hơn ấy.
2. Vội quá nên mình cũng quên mất vẽ heatmap. Cảm ơn bạn đã góp ý.

Nếu còn bất kì góp ý nào thì bạn cứ nói mình nhé!

Thanks
